FROM docker.io/library/debian:bullseye-slim

COPY samba/smb.conf /etc/samba/
COPY scripts/samba-start.sh /usr/local/bin/

RUN apt update && apt install --yes samba && apt-get clean && rm -rf /var/lib/apt/lists/* && \
    chmod +x /usr/local/bin/samba-start.sh

CMD ["/usr/local/bin/samba-start.sh"]
EXPOSE 445
