version: '3.7'

services:
  miracron:
    container_name: miracron
    build:
      context: ${MIRACRON_CONTEXT:-https://github.com/maeda577/miracron.git#main}
      dockerfile: Dockerfile.alpine
    image: localhost/miracron:latest
    volumes:
      - type: volume
        source: miracron_recorded
        target: /var/lib/miracron/recorded
      - type: bind
        source: $PWD
        target: /etc/miracron
        read_only: true
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      # 録画スケジュールを再生成するスケジュール(cron書式) (デフォルト: 毎日の午前5時)
      MIRACRON_UPDATE_SCHEDULE: "0 5 * * *"
      # ログを出力するレベル(CRITICAL, ERROR, WARNING, INFO, DEBUG のいずれか) (デフォルト: WARNING)
      MIRACRON_LOGLEVEL: INFO
      # コンフィグファイルのコンテナ内のパス(デフォルト: /etc/miracron/config.yml)
      MIRACRON_CONFIG: /etc/miracron/config.yml
      # 閲覧用のcronルールを生成するパス(デフォルト: 生成しない)
      MIRACRON_CRON_COPY: /var/lib/miracron/recorded/cron_schedule.txt
    init: true
    logging:
      driver: json-file  # お好みでjournaldに変更

  miracron-samba:
    container_name: miracron-samba
    build:
      context: ${MIRACRON_CONTEXT:-https://github.com/maeda577/miracron.git#main}
      dockerfile: Dockerfile.debian-samba
    image: localhost/miracron-samba:latest
    volumes:
      - type: volume
        source: miracron_recorded
        target: /var/lib/miracron/recorded
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      # sambaにSMBアクセスする際のrootユーザーのパスワード
      MIRACRON_SAMBA_PASSWORD: "P@ssw0rd!"
      MIRACRON_RECORDED_DIRECTORY: /var/lib/miracron/recorded
    init: true
    logging:
      driver: json-file  # お好みでjournaldに変更
    ports:
      - target: 445
        published: 445
        protocol: tcp
        mode: host

volumes:
  miracron_recorded:
