mirakurunUrl: regex('^https?://+.', required=True)
recPriority: int(required=False, none=False)
startMarginSec: int(required=False, none=False)
recordDirectory: str(required=False, none=False)
rules: list(include('rule'), required=False, none=False)
oneshots: list(int(), required=False, none=False)
---
rule:
  keywords: list(str(), required=False, none=False)
  excludeKeywords: list(str(), required=False, none=False)
  matchName: bool(required=False, none=False)
  matchDescription: bool(required=False, none=False)
  matchExtended: bool(required=False, none=False)
  serviceIds: list(int(), required=False, none=False)
